Feature/readme
harrison-ai/dataeng-handbook pull request #11
Opened 2021-10-01 06:29 UTC by doc-E-brown

## Related Tasks

N/A

## Depends on

N/A

## What

Update the README.md documentation

## Why

Explanation of the repo and documentation is required for this to be useful.

## Concerns

N/A

## Notes
N/A

2021-10-04 22:56 UTC, oliverdaff requested changes
This a clear explanation of how this repo is intended to be used :clap: .
There are a couple of changes I think are needed but just proof reading rather than structure or content.

2021-10-04 22:56 UTC, oliverdaff commented on README.md
> +* our hope is that this document may be used by others in the data engineering space as a reference or inspiration for their own methods and processes;
Should this line end with a `.` rather than a `;`?

2021-10-04 22:56 UTC, oliverdaff commented on README.md
> +This repo has been structured to allow for this document to be easily forked and customised for a number of different use cases.  As such there are a few key components and design choices that
Could this be changed to `This repo has been structured to allow this documentation ... `?

2021-10-04 22:56 UTC, oliverdaff commented on README.md
> +The other key component of this structure is the **pelican-theme** directory, or in this case git submodule.  The theme is installed as a git submodule as it allows for the theming and styling decisi
Can we add a link to git submodules incase readers are not familar with them?

2021-10-04 22:56 UTC, oliverdaff commented on README.md
> +To make a new page copy and rename the file **PAGE_TEMPLATE.md** and paste it into the **content** directory.  When renaming the file it .  Remember if you are using a sub-directory you will need at
I think `When renaming the file . Remember` should be one sentence.

2021-10-05 03:22 UTC, doc-E-brown commented on README.md
> +* our hope is that this document may be used by others in the data engineering space as a reference or inspiration for their own methods and processes;
yes

2021-10-05 03:29 UTC, oliverdaff approved these changes
:+1:

2021-10-05 03:54 UTC, merged